color_palette:
  - "dark_red=#AA0000"
  - "red=#FF5555"
  - "gold=#FFAA00"
  - "yellow=#FFFF55"
  - "dark_green=#00AA00"
  - "green=#55FF55"
  - "aqua=#55FFFF"
  - "dark_aqua=#00AAAA"
  - "dark_blue=#0000AA"
  - "blue=#5555FF"
  - "light_purple=#FF55FF"
  - "dark_purple=#AA00AA"
  - "white=#FFFFFF"
  - "gray=#AAAAAA"
  - "dark_gray=#555555"
  - "black=#000000"

allow_op_bypass_restrictions: true # op players are able to use every possible setting and color freely
allow_nc_tab_complete: true # allow people to quickly select their namecolor with tab key
enable_itemcolor: true # allow people to color their items using /ic
max_namecolor_combinations: 3 # this can be 255 at most, any larger will not work (this is only usable if gradient, flag or alternating is accessible)
default_namecolor: "gray" # this uses the same syntax as the /nc command. adding decorations is possible like so: gray italic bold (for example)

namecolor_command_texts:
  nc_info_page: "%ncname%&6, you have played for &3%pt% hours&6 and joined on &3%jd%&6 (&3%jdd% days&6 ago).\nAvailable namecolors:\n%nclist%"
  nc_unknown_color: "&cUnknown namecolor '&4%unknownnc%&c'. Use /nc for a full list of available namecolors."
  nc_invalid_deco_combos: "&cCannot combine decorations such as gradient, flag or alternating. Only one of the three can be picked."
  nc_invalid_color_amount: "&cCannot use more than %maxnc% namecolors."
  nc_invalid_color_amount_access_special_deco: "&cCannot use more than one namecolor. Use a combining modifier to use multiple colors."
  nc_invalid_color_amount_noaccess_special_deco: "&cCannot use more than one namecolor."
  nc_changed: "&6Your namecolor was changed: &r%ncname%"
  nc_no_hex_specified: "&cNo hex code was specified. \nUsage: /nc hex #FFFFFF, where #FFFFFF is your hex code."
  nc_invalid_hex_specified: "&cAn invalid hex code was specified. \nUsage: /nc hex #FFFFFF, where #FFFFFF is your hex code."
  nc_no_rgb_specified: "&cNot all RGB values were specified. \nUsage: /nc rgb 255 255 255 where the three numbers are your red, green and blue values."
  nc_invalid_component_specified: "&cAn invalid RGB color component was specified. The RGB values must be between 0 and 255 and they must be integers."
  ic_incomplete_color: "&cIncomplete color provided. Please enter a full color to use this command."
  ic_no_item_held: "&cYou are not holding any item. Ensure your mainhand has the item you want to recolor the name of before using this command."
  ic_success: "&6Your item's color was changed."

# format these like so: color_name=hours_required,days_required
# for color_name, text decorations like bold, italic, strikethrough, obfuscated and underlined are also possible
# additionally, text styles such as gradient, alternating and flag can also be used here
# custom user-defined color options such as 'hex' and 'rgb' may also be added here too
# e.g. for a color like red to be unlocked after 3 hours of playtime and 5 days joindate, it should be configured like so:
# red=3,5
# the second possible way to specify the joindate requirement is by writing the date prefixed with a capital D.
# e.g. dark_aqua=200,D8/13/2023 would make dark_aqua only unlock if the player joined before or on that date (in this case august 13th 2023)

# if the requirements of a color are not specified, it will be always available to anyone (same as setting it to 0,0)
# if the requirements of a color are negative, the color will be unobtainable unless through other means (whitelist / op)
playtime_joindate_requirements:
  # text styles:
  - "gradient=-1,-1"
  - "alternating=-1,-1"
  - "flag=-1,-1"

    # colors:
  - "dark_red=70,500"
  - "red=96,91"
  - "gold=48,46"
  - "yellow=192,183"
  - "dark_green=-1,-1"
  - "green=6,6"
  - "aqua=384,365"
  - "dark_aqua=-1,-1"
  - "dark_blue=-1,-1"
  - "blue=12,11"
  - "light_purple=-1,-1"
  - "dark_purple=24,23"
  - "white=3,3"
  - "gray=0,0"
  - "dark_gray=1536,1460"
  - "black=-1,-1"

  # text decorations:
  - "bold=384,365"
  - "underlined=-1,-1"
  - "italic=1536,1460"
  - "strikethrough=-1,-1"
  - "obfuscated=-1,-1"

  - "rgb=-1,-1"
  - "hex=-1,-1"

whitelists:
# cool_people: # any amount of whitelists with any name can be added here with each having different permissions

    # text decorations can be used here
    # custom user-defined color options such as 'hex' and 'rgb' may also be added here too
#   color_palette:
#     - "light_purple"
#     - "italic"
#     - "underlined"
#     - "dark_aqua"

    # any people on this whitelist will have access to the above listed colors, no matter their playtime or joindate or op status
#   whitelisted_users:
#     - "dc596807-4124-4946-a15c-57172943feff"
#     - "6d5453d0-9336-4801-9392-d8cf5e4136e2"
