main: org.crayne.ptjdnc.NameColorPlugin
name: PTJDNC
version: ${project.version}
api-version: 1.20
description: ${project.description}
authors: [ crayne, bierdosenhalter ]
depend: [ DonationAPI ]

commands:
  namecolor:
    description: "main namecolor command"
    aliases: ["nc"]
  itemcolor:
    description: "itemcolor command"
    aliases: ["ic"]
  opnamecolor:
    description: "namecolor command for ops to change other players nc"
    aliases: ["opnc"]