main: org.crayne.ptjdnc.NameColorPlugin
name: PTJDNC
version: 1.0
api-version: 1.19
description: "namecolor plugin inspired by 0b0t playtime namecolor for newer minecraft versions"

commands:
  namecolor:
    description: "main namecolor command"
    aliases: ["nc"]
  itemcolor:
    description: "itemcolor command"
    aliases: ["ic"]
  opnamecolor:
    description: "namecolor command for ops to change other players nc"
    aliases: ["opnc"]